hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml

https://github.com/hubblestack/nova/pull/300

Fix some tag numbers in rhel6 profile, and remove incorrect check

---

hubblestack_pulsar/hubblestack_pulsar_win_config.yaml

@mew1033 I don't know if we ever well-defined this watch list, but right now there's nothing in hubblestack_data so I figure this is a start.

Add hubblestack_pulsar_win_config.yaml from hubble-salt

---

hubblestack_nova_profiles/cis/ubuntu-1204-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/top.nova

Add provisional ubuntu 12.04 profile

---

hubblestack_nebula/hubblestack_nebula_queries.yaml

Add shell history query

---

hubblestack_nebula/hubblestack_nebula_win_queries.yaml

This is the cleaned up version of https://github.com/hubblestack/hubblestack_data/pull/19

Add new Windows queries

---

hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml

Fix for issue https://github.com/hubblestack/hubble/issues/67

Update check 7.2.6 in ubuntu 16

---

hubblestack_nova_profiles/cis/windows-2008r2-level-1-scored-v3-0-0.yaml
hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml

I have changed quite a few things on 2008 and 2012 yaml files for the modules to work better.  I have also added 2016 to the mix.  
Please note that when you merge this pull request, previous versions of windows hubble will have more failed checks due to the yaml changes.

Fixed some 2008 yaml, some 2012r2 yaml, and created 2016

---

hubblestack_nebula/hubblestack_nebula_queries.yaml
hubblestack_nebula/hubblestack_nebula_win_queries.yaml

Syntax consistency changes with previous queries.

addition of query_time and keeping sql syntax in caps, if possible

---

hubblestack_nova_profiles/cis/coreos-level-1.yaml

* Added/Updated few checks for CoreOS profile
* Removing Red Hat and Amazon specific checks from CoreOS profile

Adding more checks for CoreOS profile

---

hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml

replaced all description colons with dashes.  Fixed one line with incorrect spacing

Formatting and rogue colon fixes

---

hubblestack_pulsar/top.pulsar
hubblestack_pulsar/win_top.pulsar

Added topfiles for pulsar and win_pulsar

added topfiles for pulsar and win_pulsar

---

hubblestack_nova_profiles/cis/coreos-level-1.yaml

Adding new checks in core os profile.

Adding new checks in core os profile

---

hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml

Issue #155 fix hard returns

---

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml

On branch issue_171
modified:   amazon-level-1-scored-v2-0-0.yaml
modified:   centos-6-level-1-scored-v2-0-1.yaml
modified:   centos-7-level-1-scored-v2-0-0.yaml
modified:   centos-7-level-1-scored-v2-1-0.yaml
modified:   rhels-6-level-1-scored-v2-0-1.yaml
modified:   rhels-7-level-1-scored-v2-1-0.yaml
modified:   rhelw-7-level-1-scored-v2-1-0.yaml

Issue #171: Disable FS types should be blacklist, use /proc/modules

---

hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml
hubblestack_nova_profiles/top.nova

New centos7 profile for CIS doc 2.1.1 and incorporation checks of mount and systemctl modules

New centos7 profile (2.1.1) and incorporation of mount and systemctl checks

---

hubblestack_nebula/hubblestack_nebula_queries.yaml

Add a little more data into the suid_binaries

Add data to suid_binaries

---

hubblestack_nova_profiles/cis/windows-2012r2-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml

Added match_type on all the locations specified on the CIS documentation that allows greater than for windows firewall

Added win_firewall data to allow > in CIS specified areas

---

hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml

This is a latest RHEL 7 Server Profile For CIS Level-1 Checks.

Updated RHEL 7 Server Profile

---

hubblestack_nova_profiles/cis/windows-2008r2-level-1-scored-v1.yaml
hubblestack_nova_profiles/cis/windows-2008r2-level-1-scored-v3-0-0.yaml

Simple Windows profile fixes

---

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/coreos-level-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml

@yassingh @anuragpaliwal80 FYI.
I am merging this with my admin privileges so we can get an emergency CMR ready.

Disable all misc functions that perform global `find` commands

---

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/coreos-level-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/security/meltdown_spectre.yaml

This should remain open pending Adobe CMR.

Merge to master

---

hubblestack_nova_profiles/cve/centos-6-salt.yaml
hubblestack_nova_profiles/cve/centos-7-salt.yaml
hubblestack_nova_profiles/cve/scan-v1.yaml
hubblestack_nova_profiles/cve/scan-v2-salt.yaml
hubblestack_nova_profiles/cve/scan-v2.yaml
hubblestack_nova_profiles/cve/scan-v3.yaml
hubblestack_nova_profiles/cve/vulners.yaml
hubblestack_nova_profiles/top.nova

Ref https://github.com/hubblestack/hubble/pull/467

Deprecate all cve scans except updated vulners scanner

---

hubblestack_nebula_v2/mask.yaml

Also disable it completely by default by commenting most of it out

Update masking documentation

---

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml
hubblestack_nova_profiles/cis/debian-7.yaml
hubblestack_nova_profiles/cis/debian-9.yaml
hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml
hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml

fixup inconsistent yaml changes
change dict to list
add tag in systemctl section for audit check
remove checks with empty dictionaries
rename duplicate uid to missing gid
remove duplicate rsyslog_remote_logging audit check
rename duplicate key from rsh to rsh-server
rename duplicate key from icmp_redirect_acceptance to icmp_secure_redirect_acceptance
remove duplicate tag
rename duplicate keys

fixup inconsistent yaml changes

---

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml
hubblestack_nova_profiles/cis/debian-7.yaml
hubblestack_nova_profiles/cis/debian-9.yaml
hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml
hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml

CIS-1.7.1.1 -- Ensure message of the day is configured properly
CIS-3.2.7 -- Ensure Reverse Path Filtering is enabled
CIS-5.4.2 -- Ensure system accounts are non-login
CIS-5.4.3 -- Ensure default group for the root account is GID 0
CIS-6.2.1 -- Ensure password fields are not empty
CIS-6.2.6 -- Ensure root PATH Integrity (Scored)
CIS-6.2.7 -- Ensure all users' home directories exist (Scored)
CIS-6.2.8 -- Ensure users' home directories permissions are 750 or more restrictive (Scored)
CIS-6.2.9 -- Ensure users own their home directories (Scored)
CIS-6.2.10 -- Ensure users' dot files are not group or world writable (Scored)
CIS-6.2.11 -- Ensure no users have .forward files (Scored)
CIS-6.2.12 -- Ensure no users have .netrc files (Scored)
CIS-6.2.15 -- Ensure all groups in …

Distribution Independent Linux level 1 all v110

---

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml
hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-2-0.yaml
hubblestack_nova_profiles/cis/debian-7.yaml
hubblestack_nova_profiles/cis/debian-9.yaml
hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml
hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml
hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml
hubblestack_nova_profiles/top.nova

CIS-1.1.21 -- Ensure sticky bit is set on all world-writable directories (Scored)
CIS-1.4.3 -- Ensure authentication required for single user mode (Scored)
CIS-1.7.1.1 -- Ensure message of the day is configured properly (Scored)
CIS-3.2.7 -- Ensure Reverse Path Filtering is enabled (Scored)
CIS-4.2.4 -- Ensure permissions on all logfiles are configured (Scored)
CIS-5.4.2 -- Ensure system accounts are non-login (Scored)
CIS-5.4.3 -- Ensure default group for the root account is GID 0 (Scored)
CIS-6.2.1 -- Ensure password fields are not empty (Scored)
CIS-6.2.5 -- Ensure root is the only UID 0 account (Scored)
CIS-6.2.6 -- Ensure root PATH Integrity (Scored)
CIS-6.2.7 -- Ensure all users' home directories exist (Scored)
CIS-6.2.8 -- Ensure users' home directories …

add missing audit checks for CentOS 7 level 1 scored v220

---

hubblestack_nova_profiles/cis/windows-2012r2-level-1-scored-v2-3-0.yaml
hubblestack_nova_profiles/top.nova

Added or changed audits:
*CIS-2.2.39 -- (L1) Ensure 'Synchronize directory service data' is set to 'No One' (DC only) (Scored)
*CIS-18.6.2 -> CIS-18.3.5 -- (L1) Ensure 'WDigest Authentication' is set to 'Disabled' (Scored)
*CIS-18.3.1 -> CIS-18.4.1 -- (L1) Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon (not recommended)' is set to 'Disabled' (Scored)
*CIS-18.3.2 -> CIS-18.4.2 -- (L1) Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled' (Scored)
*CIS-18.3.3 -> CIS-18.4.3 -- (L1) Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is …

create new audit for windows 2012r2 level 1 scored v230
