hubblestack_nova_profiles/top.nova
We may add it back in once we fix our vulners code to not hammer their
servers
=> Remove cve scan v2 from default top.nova

hubblestack_nova_profiles/cis/debian-8-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/debian-8-level-1-scored-v1.yaml, hubblestack_nova_profiles/top.nova
We are seeing some debian hosts reporting "Debian GNU/Linux-8" for
osfinger
=> Fix Debian 8 matching

hubblestack_nova_profiles/top.nova
Added 2 lines to the top.nova file so server 2016 can work as seamlessly as 2008 and 2012
=> added windows 2106 to the top.nova file

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/coreos-level-1.yaml, hubblestack_nova_profiles/cis/debian-7.yaml, hubblestack_nova_profiles/cis/debian-8-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/debian-9.yaml, hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1204-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1404-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
Revision to #49 without inadvertent rollback. This time, I just used sed to edit every file. (Request #52 is included.)
```
for file in `fgrep -l sshd_conf *.yaml`; do echo $file ----; sed -i~ '/ssh.*auth_retries/,/description/{s/match_output:.*/match_output: "^MaxAuthTries +[1-4]$"/;s/match:.*/match_output: "^MaxAuthTries +[1-4]$"/;/pattern:/a\
\            match_output_regex: True
;}' $file; done 
```
Aside from my struggle with workflow, a lot of time is spent dealing with inconsistent symbols, such as "sshd_max_auth_retries" vs "ssh_auth_retries", "match_output" vs "match", even different indents. (Indents are readjusted manually not for consistence as there is none, but for in-file aesthetics.). Is the syntaxes "match_output" and "match" redundant?
=> Issue #82: Fix false positives + false negatives in sshd MaxAuthTries (3rd try)

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/debian-7.yaml, hubblestack_nova_profiles/cis/debian-8-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/debian-9.yaml, hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1204-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1404-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
I believe that all existing profiles except windows-* apply to OS' based on the Linux kernel.  So I simply applied
```
sed  -i '/fstab_.*_partition/,/description:/{s?/etc/fstab?/proc/mounts?; s/fstab_/mounts_/}' [a-u]*.yaml
```
- In this, I also replaced the internal name from fstab_*_partition* to mounts_*_partition*.  My understanding is that this does not affect output in any way.
- Those bind_mount checks cannot be done in /proc/mounts so I leave them unchanged for now. (My understanding is that CIS v2 has dropped these check (along with a bunch of others) at least for CentOS.)
=> Issue #165: Check FS options in /proc/mounts

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/debian-7.yaml, hubblestack_nova_profiles/cis/debian-8-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/debian-9.yaml, hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1204-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1404-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml
Final solution for <=300 is 0..299 or 300 (feeling lazy:-). Then the matter got even more interesting as I discovered inconsistence in match_output string, some includes key name some don't; even some headings use ssh_idle_timeout even though dealing wth sshd. This forced more general search strings and a fixing of headings. Fortunately the variations stop there. Anyway, here's the formula
```
fgrep -l ClientAliveInterval *.yaml |xargs sed -i~ '/_idle_timeout:/,/description:/{s/ssh_idle_timeout:/sshd_idle_timeout:/; s/match_output:.*[^0-9]0[^0-9]*$/match_output: "^ClientAliveCountMax +[0-3]$"/;  s/match_output:.*300.*/match_output: ^ClientAliveInterval +([1-2]{0,1}\d{1,2}|300)$/;/match_output:.*ClientAlive/a\                               
\            match_output_regex: True
;}'
``` …
=> Issue #179 (3rd try): sshd_idle_timeout should use regex with boundary, range

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/coreos-level-1.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml
Also fixed two related problems.
- Some profiles used sshd_login_grace as label; I go with majority, sshd_gracetime.
- Some profiles also did not anchor `pattern`; when combined with literal `match_output`, this can lead to more possible negatives when valid range is placed in comments.
`
fgrep -l LoginGraceTime *.yaml
| xargs sed i~ 's/sshd_login_grace:/sshd_gracetime:/;/LoginGraceTime/,/description/{s/pattern: .*/pattern: ^LoginGraceTime/; s/match_output:.*/match_output: ^LoginGraceTime ([0-5]{0,1}\\d|60|1m)$/; /match_output:/a\
\            match_output_regex: True
; }'
`
followed by manually fixing jagged indents.
On branch sshd_gracetime
modified:   hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml
modified:   hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1. …
=> Issue #188: Use regex for sshd_gracetime (and related fixes)

hubblestack_nova_profiles/cis/windows-2012r2-level-1-scored-v2-0-0.yaml
match is not a valid value_type
=> set value_type to account for CIS-2.2.5

hubblestack_nova_profiles/security/meltdown_spectre.yaml, hubblestack_nova_profiles/security/pcid.yaml, hubblestack_nova_profiles/top.nova
This adds a new check to look for pcid support in /proc/cpuinfo. This information can help when triaging systems for Meltdown/Spectre.
This is modifying the top.nova file. I've tested it and it seems to work, but we should definitely have a few more eyes on this before merging.
=> Add PCID check for meltdown/spectre

hubblestack_nova_profiles/security/meltdown_spectre.yaml
Per RedHat, spectre v1 mitigation cannot be disabled, just presence
of the new kernel is enough. We have redundant checks just to have
parity with other checks.
=> Meltdown/Spectre checks: centos/rhel spectre v1 checks

hubblestack_nova_profiles/security/meltdown_spectre.yaml
Escaping spaces matters - otherwise the results can be opposite.
=> Meltdown/Spectre checks: fix escaping spaces in patterns

hubblestack_nebula/hubblestack_nebula_win_queries.yaml
@madchills This should fix the thing. Can you run this query on a win 2012 and 2008 box to make sure it works?
SELECT t.unix_time AS query_time, si.uuid, si.cpu_type, si.cpu_subtype, si.cpu_brand, si.cpu_physical_cores, si.cpu_logical_cores, si.hardware_vendor, si.hardware_serial, si.hardware_model, (SELECT value FROM cpuid WHERE feature = 'hypervisor') AS virtual_machine, t.local_timezone AS local_timezone FROM system_info AS si, time AS t;
=> Fix win_system_info query

hubblestack_nova_profiles/cis/amazon-201409-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml, hubblestack_nova_profiles/cis/debian-7.yaml, hubblestack_nova_profiles/cis/debian-9.yaml, hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml, hubblestack_nova_profiles/cis/rhels-5-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-6-level-1-scored-v2-0-1.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhelw-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-1-0.yaml, hubblestack_nova_profiles/cis/windows-2016-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/top.nova
*CIS-1.1.13 Ensure nodev option set on /home partition (Scored)
*CIS-1.4.2 -- Ensure bootloader password is set (Scored)
*CIS-1.4.3 -- Ensure authentication required for single user mode (Scored)
*CIS-2.1.11 -- Ensure openbsd-inetd is not installed (Scored)
*CIS-2.2.1.3 -- Ensure chrony is configured (Scored)
*CIS-4.2.2.1 -- Ensure syslog-ng service is enabled (Scored)
*CIS-4.2.2.3 -- Ensure syslog-ng default file permissions configured (Scored)
*CIS-5.3.2 -- Ensure lockout for failed password attempts is configured (Scored)
Checks not added:
CIS-1.1.20 -- Ensure sticky bit is set on all world-writable directories (Scored)
CIS-1.7.2 Ensure GDM login banner is configured (Scored)
CIS-3.6.5 Ensure firewall rules exist for all open ports (Scored)
CIS-5.4.1.5 Ensure all …
=> add new audit for latest ubuntu 1604 level 1 scored v110

hubblestack_nova_profiles/cis/ubuntu-1804-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/top.nova
Taking another stab at this one
CIS-1.7.1.2 -- Ensure local login warning banner is configured properly (Scored)
CIS-1.7.1.3 -- Ensure remote login warning banner is configured properly (Scored)
CIS-1.7.1.4 -- Ensure permissions on /etc/motd are configured (Scored)
CIS-1.7.1.6 -- Ensure permissions on /etc/issue.net are configured (Scored)
Checks not added:
CIS-1.1.20 -- Ensure sticky bit is set on all world-writable directories (Scored)
CIS-1.7.2 -- Ensure GDM login banner is configured (Scored)
CIS-3.6.5 -- Ensure firewall rules exist for all open ports (Scored)
CIS-5.4.1.5 -- Ensure all users last password change date is in the past (Scored)
CIS-6.1.10 -- Ensure no world writable files exist (Scored)
CIS-6.1.11 -- Ensure no unowned files or directories exist (Scored) …
=> add new audit for latest ubuntu 1804 level 1 scored v100

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/top.nova
Made this the default selection for 2016, 2017, and 2018 AMIs
CIS-4.2.4	Ensure permissions on all logfiles are configured (Scored)
CIS-6.2.6 -- Ensure root PATH Integrity (Scored)
CIS-6.2.7 -- Ensure all users' home directories exist (Scored)
CIS-6.2.8 -- Ensure users' home directories permissions are 750 or more restrictive (Scored)
CIS-6.2.9 -- Ensure users own their home directories (Scored)
CIS-6.2.10 -- Ensure users' dot files are not group or world writable (Scored)
CIS-6.2.11 -- Ensure no users have .forward files (Scored)
CIS-6.2.12 -- Ensure no users have .netrc files (Scored)
CIS-6.2.13 -- Ensure users' .netrc Files are not group or world accessible (Scored)
CIS-6.2.14 -- Ensure no users have .rhosts files (Scored)
CIS-6.2.15 -- Ensure all groups in /etc/passwd …
=> add missing audits for amazon level 1 v210

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/coreos-level-1.yaml, hubblestack_nova_profiles/cis/debian-9-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1804-level-1-scored-v1-0-0.yaml
Once we figure out the problematic check we'll get these uncommented
again.
=> Disable all misc.py checks by default (due to performance concerns)

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-0-0.yaml, hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-1-1.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/coreos-level-1.yaml, hubblestack_nova_profiles/cis/debian-9-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1804-level-1-scored-v1-0-0.yaml
We had a host with a bunch of stuff in the dotfiles of a system user and
the find command called by this check was impacting the system.
We'll need to figure out a safer way to do this check.
This also reverts https://github.com/hubblestack/hubblestack_data/pull/146 which was too broad.
=>  Disable check_users_dot_files checks

hubblestack_nova_profiles/cis/amazon-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/coreos-level-1.yaml, hubblestack_nova_profiles/cis/debian-9-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/distribution-independent-linux-level-1-all-v1-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-1-0.yaml, hubblestack_nova_profiles/cis/rhels-7-level-1-scored-v2-2-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-1-0.yaml, hubblestack_nova_profiles/cis/ubuntu-1804-level-1-scored-v1-0-0.yaml
This has had some edge case issues -- if you have many files under
/var/log then this `find` command can hobble your system. We need to
find a more safe way to do this check.
=> Disable /var/log permission check

hubblestack_nova_profiles/cis/centos-7-level-1-scored-v2-2-0.yaml
This Check is no longer required in version 2.2.0
=> CIS-5.2.11.1 was removed in version 2.2.0

hubblestack_nova_profiles/security/meltdown_spectre.yaml
This pr will do the following:
* add checks for detecting if the host is vulnerable for mds attacks (CVE-2018-12130)
* fix/improve l1ft vulnerability checks (CVE-2018-3620)
These checks were tested on a vulnerable and not vulnerable host.
=> add mds and fix l1tf vulnerability checks
